package fr.doranco.ecommerce;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;
import org.springframework.context.ApplicationContext;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn

@SpringBootApplication
public class ECommerceApplication extends SpringBootServletInitializer {
    public static void main(String[] args) throws SQLException {
        SpringApplication.run(ECommerceApplication.class, args);

        try (Connection con = DriverManager
                .getConnection("jdbc:mysql://localhost:8080", "root", "")) {
            // use con here
        }
    }

    @Override
    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
        return application.sources(ECommerceApplication.class);
    }

}
