package fr.doranco.ecommerce;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn

@SpringBootApplication
public class ECommerceApplication {

	public static void main(String[] args) throws SQLException {
		SpringApplication.run(ECommerceApplication.class, args);
		
		try (Connection con = DriverManager
				  .getConnection("jdbc:mysql://localhost:8080", "root", "")) {
				    // use con here
				}
	}

}
